//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Actors = newActorsTable("public", "actors", "")

type actorsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Type      postgres.ColumnString
	UpdatedAt postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ActorsTable struct {
	actorsTable

	EXCLUDED actorsTable
}

// AS creates new ActorsTable with assigned alias
func (a ActorsTable) AS(alias string) *ActorsTable {
	return newActorsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ActorsTable with assigned schema name
func (a ActorsTable) FromSchema(schemaName string) *ActorsTable {
	return newActorsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ActorsTable with assigned table prefix
func (a ActorsTable) WithPrefix(prefix string) *ActorsTable {
	return newActorsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ActorsTable with assigned table suffix
func (a ActorsTable) WithSuffix(suffix string) *ActorsTable {
	return newActorsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newActorsTable(schemaName, tableName, alias string) *ActorsTable {
	return &ActorsTable{
		actorsTable: newActorsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newActorsTableImpl("", "excluded", ""),
	}
}

func newActorsTableImpl(schemaName, tableName, alias string) actorsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		TypeColumn      = postgres.StringColumn("type")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, TypeColumn, UpdatedAtColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{TypeColumn, UpdatedAtColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return actorsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Type:      TypeColumn,
		UpdatedAt: UpdatedAtColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
