//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ServiceAccounts = newServiceAccountsTable("public", "service_accounts", "")

type serviceAccountsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	CorrelationID postgres.ColumnString
	ActorID       postgres.ColumnString
	BusinessID    postgres.ColumnString
	Label         postgres.ColumnString
	Status        postgres.ColumnString
	CredentialRef postgres.ColumnString
	UpdatedAt     postgres.ColumnTimestampz
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ServiceAccountsTable struct {
	serviceAccountsTable

	EXCLUDED serviceAccountsTable
}

// AS creates new ServiceAccountsTable with assigned alias
func (a ServiceAccountsTable) AS(alias string) *ServiceAccountsTable {
	return newServiceAccountsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ServiceAccountsTable with assigned schema name
func (a ServiceAccountsTable) FromSchema(schemaName string) *ServiceAccountsTable {
	return newServiceAccountsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ServiceAccountsTable with assigned table prefix
func (a ServiceAccountsTable) WithPrefix(prefix string) *ServiceAccountsTable {
	return newServiceAccountsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ServiceAccountsTable with assigned table suffix
func (a ServiceAccountsTable) WithSuffix(suffix string) *ServiceAccountsTable {
	return newServiceAccountsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newServiceAccountsTable(schemaName, tableName, alias string) *ServiceAccountsTable {
	return &ServiceAccountsTable{
		serviceAccountsTable: newServiceAccountsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newServiceAccountsTableImpl("", "excluded", ""),
	}
}

func newServiceAccountsTableImpl(schemaName, tableName, alias string) serviceAccountsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		CorrelationIDColumn = postgres.StringColumn("correlation_id")
		ActorIDColumn       = postgres.StringColumn("actor_id")
		BusinessIDColumn    = postgres.StringColumn("business_id")
		LabelColumn         = postgres.StringColumn("label")
		StatusColumn        = postgres.StringColumn("status")
		CredentialRefColumn = postgres.StringColumn("credential_ref")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, CorrelationIDColumn, ActorIDColumn, BusinessIDColumn, LabelColumn, StatusColumn, CredentialRefColumn, UpdatedAtColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{CorrelationIDColumn, ActorIDColumn, BusinessIDColumn, LabelColumn, StatusColumn, CredentialRefColumn, UpdatedAtColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return serviceAccountsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CorrelationID: CorrelationIDColumn,
		ActorID:       ActorIDColumn,
		BusinessID:    BusinessIDColumn,
		Label:         LabelColumn,
		Status:        StatusColumn,
		CredentialRef: CredentialRefColumn,
		UpdatedAt:     UpdatedAtColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
