//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Classifications struct {
	ID         string `sql:"primary_key"`
	BusinessID string
	Axis       string
	Value      string
	UpdatedAt  time.Time
	CreatedAt  time.Time
}
