//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Businesses = newBusinessesTable("public", "businesses", "")

type businessesTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	CorrelationID     postgres.ColumnString
	LegalName         postgres.ColumnString
	TradeName         postgres.ColumnString
	CrNumber          postgres.ColumnString
	LegalForm         postgres.ColumnString
	IncorporationDate postgres.ColumnTimestampz
	Status            postgres.ColumnString
	OrganizationID    postgres.ColumnString
	KeycloakOrgID     postgres.ColumnString
	LedgerRef         postgres.ColumnString
	UpdatedAt         postgres.ColumnTimestampz
	CreatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BusinessesTable struct {
	businessesTable

	EXCLUDED businessesTable
}

// AS creates new BusinessesTable with assigned alias
func (a BusinessesTable) AS(alias string) *BusinessesTable {
	return newBusinessesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BusinessesTable with assigned schema name
func (a BusinessesTable) FromSchema(schemaName string) *BusinessesTable {
	return newBusinessesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BusinessesTable with assigned table prefix
func (a BusinessesTable) WithPrefix(prefix string) *BusinessesTable {
	return newBusinessesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BusinessesTable with assigned table suffix
func (a BusinessesTable) WithSuffix(suffix string) *BusinessesTable {
	return newBusinessesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBusinessesTable(schemaName, tableName, alias string) *BusinessesTable {
	return &BusinessesTable{
		businessesTable: newBusinessesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newBusinessesTableImpl("", "excluded", ""),
	}
}

func newBusinessesTableImpl(schemaName, tableName, alias string) businessesTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		CorrelationIDColumn     = postgres.StringColumn("correlation_id")
		LegalNameColumn         = postgres.StringColumn("legal_name")
		TradeNameColumn         = postgres.StringColumn("trade_name")
		CrNumberColumn          = postgres.StringColumn("cr_number")
		LegalFormColumn         = postgres.StringColumn("legal_form")
		IncorporationDateColumn = postgres.TimestampzColumn("incorporation_date")
		StatusColumn            = postgres.StringColumn("status")
		OrganizationIDColumn    = postgres.StringColumn("organization_id")
		KeycloakOrgIDColumn     = postgres.StringColumn("keycloak_org_id")
		LedgerRefColumn         = postgres.StringColumn("ledger_ref")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		allColumns              = postgres.ColumnList{IDColumn, CorrelationIDColumn, LegalNameColumn, TradeNameColumn, CrNumberColumn, LegalFormColumn, IncorporationDateColumn, StatusColumn, OrganizationIDColumn, KeycloakOrgIDColumn, LedgerRefColumn, UpdatedAtColumn, CreatedAtColumn}
		mutableColumns          = postgres.ColumnList{CorrelationIDColumn, LegalNameColumn, TradeNameColumn, CrNumberColumn, LegalFormColumn, IncorporationDateColumn, StatusColumn, OrganizationIDColumn, KeycloakOrgIDColumn, LedgerRefColumn, UpdatedAtColumn, CreatedAtColumn}
		defaultColumns          = postgres.ColumnList{}
	)

	return businessesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		CorrelationID:     CorrelationIDColumn,
		LegalName:         LegalNameColumn,
		TradeName:         TradeNameColumn,
		CrNumber:          CrNumberColumn,
		LegalForm:         LegalFormColumn,
		IncorporationDate: IncorporationDateColumn,
		Status:            StatusColumn,
		OrganizationID:    OrganizationIDColumn,
		KeycloakOrgID:     KeycloakOrgIDColumn,
		LedgerRef:         LedgerRefColumn,
		UpdatedAt:         UpdatedAtColumn,
		CreatedAt:         CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
