//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Invitations = newInvitationsTable("public", "invitations", "")

type invitationsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	CorrelationID postgres.ColumnString
	BusinessID    postgres.ColumnString
	InvitedEmail  postgres.ColumnString
	IntendedRole  postgres.ColumnString
	Token         postgres.ColumnString
	Status        postgres.ColumnString
	InvitedBy     postgres.ColumnString
	ExpiresAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type InvitationsTable struct {
	invitationsTable

	EXCLUDED invitationsTable
}

// AS creates new InvitationsTable with assigned alias
func (a InvitationsTable) AS(alias string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InvitationsTable with assigned schema name
func (a InvitationsTable) FromSchema(schemaName string) *InvitationsTable {
	return newInvitationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InvitationsTable with assigned table prefix
func (a InvitationsTable) WithPrefix(prefix string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InvitationsTable with assigned table suffix
func (a InvitationsTable) WithSuffix(suffix string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInvitationsTable(schemaName, tableName, alias string) *InvitationsTable {
	return &InvitationsTable{
		invitationsTable: newInvitationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newInvitationsTableImpl("", "excluded", ""),
	}
}

func newInvitationsTableImpl(schemaName, tableName, alias string) invitationsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		CorrelationIDColumn = postgres.StringColumn("correlation_id")
		BusinessIDColumn    = postgres.StringColumn("business_id")
		InvitedEmailColumn  = postgres.StringColumn("invited_email")
		IntendedRoleColumn  = postgres.StringColumn("intended_role")
		TokenColumn         = postgres.StringColumn("token")
		StatusColumn        = postgres.StringColumn("status")
		InvitedByColumn     = postgres.StringColumn("invited_by")
		ExpiresAtColumn     = postgres.TimestampzColumn("expires_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, CorrelationIDColumn, BusinessIDColumn, InvitedEmailColumn, IntendedRoleColumn, TokenColumn, StatusColumn, InvitedByColumn, ExpiresAtColumn, UpdatedAtColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{CorrelationIDColumn, BusinessIDColumn, InvitedEmailColumn, IntendedRoleColumn, TokenColumn, StatusColumn, InvitedByColumn, ExpiresAtColumn, UpdatedAtColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return invitationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CorrelationID: CorrelationIDColumn,
		BusinessID:    BusinessIDColumn,
		InvitedEmail:  InvitedEmailColumn,
		IntendedRole:  IntendedRoleColumn,
		Token:         TokenColumn,
		Status:        StatusColumn,
		InvitedBy:     InvitedByColumn,
		ExpiresAt:     ExpiresAtColumn,
		UpdatedAt:     UpdatedAtColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
