//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Actors = Actors.FromSchema(schema)
	Businesses = Businesses.FromSchema(schema)
	Classifications = Classifications.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Invitations = Invitations.FromSchema(schema)
	Memberships = Memberships.FromSchema(schema)
	Organizations = Organizations.FromSchema(schema)
	ServiceAccounts = ServiceAccounts.FromSchema(schema)
}
