//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Businesses struct {
	ID                string `sql:"primary_key"`
	CorrelationID     string
	LegalName         string
	TradeName         string
	CrNumber          string
	LegalForm         string
	IncorporationDate *time.Time
	Status            string
	OrganizationID    *string
	KeycloakOrgID     *string
	LedgerRef         *string
	UpdatedAt         time.Time
	CreatedAt         time.Time
}
