//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Classifications = newClassificationsTable("public", "classifications", "")

type classificationsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	BusinessID postgres.ColumnString
	Axis       postgres.ColumnString
	Value      postgres.ColumnString
	UpdatedAt  postgres.ColumnTimestampz
	CreatedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ClassificationsTable struct {
	classificationsTable

	EXCLUDED classificationsTable
}

// AS creates new ClassificationsTable with assigned alias
func (a ClassificationsTable) AS(alias string) *ClassificationsTable {
	return newClassificationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ClassificationsTable with assigned schema name
func (a ClassificationsTable) FromSchema(schemaName string) *ClassificationsTable {
	return newClassificationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ClassificationsTable with assigned table prefix
func (a ClassificationsTable) WithPrefix(prefix string) *ClassificationsTable {
	return newClassificationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ClassificationsTable with assigned table suffix
func (a ClassificationsTable) WithSuffix(suffix string) *ClassificationsTable {
	return newClassificationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newClassificationsTable(schemaName, tableName, alias string) *ClassificationsTable {
	return &ClassificationsTable{
		classificationsTable: newClassificationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newClassificationsTableImpl("", "excluded", ""),
	}
}

func newClassificationsTableImpl(schemaName, tableName, alias string) classificationsTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		BusinessIDColumn = postgres.StringColumn("business_id")
		AxisColumn       = postgres.StringColumn("axis")
		ValueColumn      = postgres.StringColumn("value")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		allColumns       = postgres.ColumnList{IDColumn, BusinessIDColumn, AxisColumn, ValueColumn, UpdatedAtColumn, CreatedAtColumn}
		mutableColumns   = postgres.ColumnList{BusinessIDColumn, AxisColumn, ValueColumn, UpdatedAtColumn, CreatedAtColumn}
		defaultColumns   = postgres.ColumnList{}
	)

	return classificationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		BusinessID: BusinessIDColumn,
		Axis:       AxisColumn,
		Value:      ValueColumn,
		UpdatedAt:  UpdatedAtColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
