//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Memberships = newMembershipsTable("public", "memberships", "")

type membershipsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	CorrelationID postgres.ColumnString
	ActorID       postgres.ColumnString
	BusinessID    postgres.ColumnString
	KeycloakSub   postgres.ColumnString
	PersonID      postgres.ColumnString
	Role          postgres.ColumnString
	Status        postgres.ColumnString
	UpdatedAt     postgres.ColumnTimestampz
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MembershipsTable struct {
	membershipsTable

	EXCLUDED membershipsTable
}

// AS creates new MembershipsTable with assigned alias
func (a MembershipsTable) AS(alias string) *MembershipsTable {
	return newMembershipsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MembershipsTable with assigned schema name
func (a MembershipsTable) FromSchema(schemaName string) *MembershipsTable {
	return newMembershipsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MembershipsTable with assigned table prefix
func (a MembershipsTable) WithPrefix(prefix string) *MembershipsTable {
	return newMembershipsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MembershipsTable with assigned table suffix
func (a MembershipsTable) WithSuffix(suffix string) *MembershipsTable {
	return newMembershipsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMembershipsTable(schemaName, tableName, alias string) *MembershipsTable {
	return &MembershipsTable{
		membershipsTable: newMembershipsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newMembershipsTableImpl("", "excluded", ""),
	}
}

func newMembershipsTableImpl(schemaName, tableName, alias string) membershipsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		CorrelationIDColumn = postgres.StringColumn("correlation_id")
		ActorIDColumn       = postgres.StringColumn("actor_id")
		BusinessIDColumn    = postgres.StringColumn("business_id")
		KeycloakSubColumn   = postgres.StringColumn("keycloak_sub")
		PersonIDColumn      = postgres.StringColumn("person_id")
		RoleColumn          = postgres.StringColumn("role")
		StatusColumn        = postgres.StringColumn("status")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, CorrelationIDColumn, ActorIDColumn, BusinessIDColumn, KeycloakSubColumn, PersonIDColumn, RoleColumn, StatusColumn, UpdatedAtColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{CorrelationIDColumn, ActorIDColumn, BusinessIDColumn, KeycloakSubColumn, PersonIDColumn, RoleColumn, StatusColumn, UpdatedAtColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return membershipsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CorrelationID: CorrelationIDColumn,
		ActorID:       ActorIDColumn,
		BusinessID:    BusinessIDColumn,
		KeycloakSub:   KeycloakSubColumn,
		PersonID:      PersonIDColumn,
		Role:          RoleColumn,
		Status:        StatusColumn,
		UpdatedAt:     UpdatedAtColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
