//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Memberships struct {
	ID            string `sql:"primary_key"`
	CorrelationID string
	ActorID       string
	BusinessID    string
	KeycloakSub   string
	PersonID      *string
	Role          string
	Status        string
	UpdatedAt     time.Time
	CreatedAt     time.Time
}
